# This workflow automates CMake build testing for all folders with CMakeLists.txt
name: CMake Build Test in All Folders

on:
  # Triggers the workflow on push, pull request events, or manual dispatch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Debug  # Customize the CMake build type (Release, Debug, etc.)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Folders with CMakeLists.txt
        run: |
          FOLDERS=$(find . -type f -name "CMakeLists.txt" | xargs -n1 dirname)
          if [[ -z "$FOLDERS" ]]; then
            echo "Error: No project folders with CMakeLists.txt found!"
            exit 1
          fi
          echo "Valid project folders found:"
          echo "$FOLDERS"
        shell: bash
              
      - name: Install arm-none-eabi-gcc GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@main
        
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Check Tool Versions
        run: |
          echo "::group::Checking tool versions"
          arm-none-eabi-gcc --version
          ninja --version
          echo "::endgroup::"

      - name: Configure and Build Projects
        run: |
          for dir in $FOLDERS; do
            echo "::group::Processing folder: $dir"
            cmake -B "$GITHUB_WORKSPACE/$dir/build" -S "$GITHUB_WORKSPACE/$dir" -DCMAKE_BUILD_TYPE="${{ env.BUILD_TYPE }}"
            cmake --build "$GITHUB_WORKSPACE/$dir/build" --config "${{ env.BUILD_TYPE }}" -- -j$(nproc)
            echo "::endgroup::"
          done
        shell: bash
